org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17.19
fabric_version=0.155.2+26.1.2
fabric_min_version=0.145.4
modmenu_version=18.0.0
jei_version=29.16.0.47
mod_version=26.1.2-2.7.0-fabric
maven_group=twopiradians.blockArmor
archives_base_name=block-armor
